//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
        [Required]
        [DisplayName("Mã Sản Phẩm")]
        public string MaSanPham { get; set; }
        [Required]
        [DisplayName("Tên Sản Phẩm")]
        public string TenSanPham { get; set; }
        [Required]
        [DisplayName("Loại Sản Phẩm")]
        public string MaPhanLoai { get; set; }
        [Required]
        [DisplayName("Giá Nhập")]
        public Nullable<long> GiaNhap { get; set; }
        [Required]
        [DisplayName("Giá Bán Nhỏ Nhất")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }
        [Required]
        [DisplayName("Giá Bán Lớn Nhất")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }
        [Required]
        [DisplayName("Trạng Thái")]
        public Nullable<bool> TrangThai { get; set; }
        [Required]
        [DisplayName("Mô Tả")]
        public string MoTaNgan { get; set; }
        [DisplayName("Ảnh")]
        public string AnhDaiDien { get; set; }
        [Required]
        [DisplayName("Sản Phẩm Nổi Bật")]
        public Nullable<bool> NoiBat { get; set; }
        [Required]
        [DisplayName("Tên Sản Phẩm")]
        public string MaPhanLoaiPhu { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }
    }
}
